---
control:
  hosts:
    localhost:
      ansible_connection: local
centos:
  hosts:
    centos1:
      # ansible_port: 2222 In case ssh is changed
    centos2:
    centos3:
  vars:
    ansible_user: root
ubuntu:
  hosts:
    ubuntu1:
    ubuntu2:
    ubuntu3:
  vars:
    ansible_user: packt
    ansible_become: true
    ansible_become_pass: password
linux:
  children:
    centos:
    ubuntu:
  vars:
    ansible_ssh_pass: password

all:
  vars:
    ansible_connection: ssh
...